# Generated by Django 5.1.3 on 2025-08-08 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=40)),
                ('reps', models.IntegerField()),
                ('sets', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('exercise_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_zones_major', models.CharField(max_length=100, null=True)),
                ('target_zones_minor', models.CharField(blank=True, max_length=100, null=True)),
                ('equipment', models.CharField(default='None', max_length=100)),
                ('category', models.ManyToManyField(to='quest_app.exercisecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=10)),
                ('exe_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest_app.exercisecategory')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest_app.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest_app.dayplan')),
                ('exercises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest_app.exercise')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest_app.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_day', models.IntegerField(null=True)),
                ('workout_completed', models.BooleanField(default=False)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest_app.dayplan')),
                ('user_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest_app.status')),
            ],
        ),
    ]
