# Generated by Django 5.1.3 on 2025-04-01 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_rename_profile_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_type', models.CharField(choices=[('PH', 'Physical health'), ('MH', 'Mental health')], default='PH', max_length=20)),
                ('UserProfile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(blank=True, choices=[('Push-ups', 'Push-ups'), ('Pull-ups', 'Pull-ups'), ('Bench Press', 'Bench Press')], max_length=20)),
                ('Category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_app.setgoal')),
            ],
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports_name', models.CharField(blank=True, choices=[('Running', 'Running'), ('Swimming', 'Swimming')], max_length=20)),
                ('Category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_app.setgoal')),
            ],
        ),
    ]
