# Generated by Django 5.1.3 on 2025-04-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_setgoal_exercise_sports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sports',
            name='Category_id',
        ),
        migrations.AddField(
            model_name='setgoal',
            name='exercise_name',
            field=models.CharField(blank=True, choices=[('Push-ups', 'Push-ups'), ('Pull-ups', 'Pull-ups'), ('Bench Press', 'Bench Press')], max_length=20),
        ),
        migrations.AddField(
            model_name='setgoal',
            name='sports_name',
            field=models.CharField(blank=True, choices=[('Running', 'Running'), ('Swimming', 'Swimming')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='Sports',
        ),
    ]
